### ISSUE TITLE
[data grid] React 19 support

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#13356]
## React 19 demos

- [`DataGrid`](https://codesandbox.io/p/sandbox/intelligent-jerry-2jgvqy)
- [`DataGridPro`](https://codesandbox.io/p/sandbox/late-cookies-8y8j2d)
- [`DataGridPremium`](https://codesandbox.io/p/sandbox/inspiring-grothendieck-xxjryc)

## Issues

- [x] "Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release."
  Example: https://codesandbox.io/p/sandbox/intelligent-jerry-2jgvqy
  https://github.com/mui/material-ui/issues/42604

- [x] "Rendered fewer hooks than expected."
  Reproducible in both `DataGridPro` and `DataGridPremium`, but not in `DataGrid`.
  Example: https://codesandbox.io/p/sandbox/late-cookies-8y8j2d
  No warnings in React 18.3.1: https://codesandbox.io/p/sandbox/cool-dream-4zznnh 
  
## TODO

- [x] Support running our testing suite against different React versions (borrow the solution from the core? https://github.com/mui/material-ui/pull/25005)
  **Draft PR**: https://github.com/mui/mui-x/pull/13360
- [x] Update test compatible with React 19
  **Reference Material UI PR**: https://github.com/mui/material-ui/pull/43155
- [ ] Make sure Material UI v5 supports React 19 https://github.com/mui/material-ui/issues/42381
- [x] Update `peerDependencies` to include `^19.0.0` once data grid works with React 19

**Search keywords**:

**Comment by arminmeh** [comment]
@cherniavskii are you able to reproduce the `Rendered fewer hooks than expected.` error locally?
For me, this specific issue does not appear locally (copy of https://codesandbox.io/p/sandbox/late-cookies-8y8j2d) and even on the sandbox grid starts working after you start making some code changes.
Maybe it is only a sandbox related issue for the initial load?

**Comment by cherniavskii** [comment]
@arminmeh Indeed, I can't reproduce it when running the codesandbox locally.
But it also doesn't seem to be using React 19:
```sh
$ npm ls
├── @emotion/react@11.13.3
├── @emotion/styled@11.13.0
├── @mui/icons-material@6.0.2
├── @mui/material@6.0.2
├── @mui/x-data-grid-generator@7.16.0
├── @mui/x-data-grid-pro@7.16.0
├── @types/react-dom@18.3.0
├── @types/react@18.3.5
├── react-dom@18.3.1
├── react-scripts@5.0.1
├── react@18.3.1
└── typescript@4.9.5
```

Not sure why though 🤔

**Comment by oliviertassinari** [comment]
With https://nextjs.org/blog/next-15 stable, and used at 10% https://tools-public.mui.com/prod/pages/npmVersion?package=next, we might want to prioritize more.
