### ISSUE TITLE
[DataGrid] Bundle size is way too large

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#18]
The current bundle size and bundling strategy is not flying. It's not living up to the quality level our audience expects from the core components. https://bundlephobia.com/result?p=@material-ui/data-grid

## Tree-shaking

First, tree-shaking is not working. (tested with CRA). This means that, for instance, developers bundle all the locales. I think that the solution is to drop the current bundling strategy and copy what the core is doing. I think that this bundling problem is hard enough, we don't have the resources to solve the problems twice because we use two different solutions between different packages.

**in**

```jsx
import * as React from 'react';
import { GridToolbar } from '@material-ui/data-grid';

export default function DataGridDemo() {
  console.log('GridToolbar', GridToolbar)
  return null;
}
```

**out**, in the production bundle

<img width="466" alt="Screenshot 2021-04-24 at 20 16 03" src="https://user-images.githubusercontent.com/3165635/115968824-ec3be800-a539-11eb-8695-bea8c7dba7ad.png">

<img width="686" alt="Capture d’écran 2021-06-12 à 12 44 35" src="https://user-images.githubusercontent.com/3165635/121773390-f793b300-cb7b-11eb-9b3c-28b5e4adf955.png">

## Inefficiencies

Second, here is a couple of bundle size-reduction opportunities:

- [x] **clsx**. (win ~0.3 kB gzipped) Replace classnames with clsx.
- [ ] **license**. (win ~0.7 kB) I believe we can remove the need from including `packages/license/src/encoding/base64.ts` in the bundle of the users. The possible solution would work as follow:
  - client-side, use the built-in `window.atob` and `window.btoa`, only run the license check if the window is defined (ignore server-side, and CI)
  - server-side, us the built-in `Buffer.from('Hello World!').toString('base64');` and `Buffer.from(b64Encoded, 'base64').toString()` utils.
- [x] **lodash**. The dependency was inlined in the repository (I guess to hide, [on the surface](https://npm.anvaka.com/#/view/2d/%2540material-ui-x%252Fgrid), the dependency on this library), I don't think that it removes the fact that we depend on it. I would be in favor of completely removing its modules from the codebase.
  Recommended migration plan:
- [x] **denounce**. (win ~ (0.5 kB) Instead of the [938 B](https://bundlephobia.com/result?p=lodash.debounce@4.0.8) version of lodash we could rely on the [305 B](https://bundlephobia.com/result?p=@material-ui/core@4.10.0) `import { denounce } from @material-ui/core` module. We could also move the module to `@material-ui/utils` instead of the core if that makes more sense. This module also has the advantage of being deduplicated with the core components, sharing the simple source.
- [x] **deep equal**. (win ~3.5 kB gzipped) Instead of the [3.8 Kb](https://bundlephobia.com/result?p=lodash.isequal@4.5.0) version of lodash, we could replace it with [fast-deep-equal](https://github.com/epoberezkin/fast-deep-equal), a [414 B](https://bundlephobia.com/result?p=fast-deep-equal@3.1.1) alternative. I have only seen one use case in the codebase, I even wonder if we couldn't use JSON.stringify directly (see #3954)
- [ ] **Select**. (win ~0.5 kB gzipped) Replace Select import with NativeSelect).
- [ ] **TextField** (win ~5 kB gzipped). Replace TextField with individual imports, allow dropping `OutlinedInput` and `FilledInput` from the bundle..
- [x] **Babel** (win ~0.6 kB gzipped) Remove propTypes in production with this [Babel plugin](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types).

https://github.com/mui-org/material-ui-x/blob/fb5af45b5d74ca818fc6945af17400cec0ee21a2/packages/grid/src/hooks/root/useColumns.tsx#L162

**Comment by flaviendelangle** [comment]
Do we have a plan to avoid bundling all the locales for the Grid ?

**Comment by oliviertassinari** [comment]
> Do we have a plan to avoid bundling all the locales for the Grid ?

@flaviendelangle I don't know why tree-shaking is not working. Fixing it would fix the locales issue. Actually, seeing that bgBG is this large, it suggests also that something is wrong at this layer. Intuitively, a locale is only 100 lines. Maybe it's because of

```diff
diff --git a/packages/grid/_modules_/grid/utils/getGridLocalization.ts b/packages/grid/_modules_/grid/utils/getGridLocalization.ts
index 8fb0dcaf..0f5ad824 100644
--- a/packages/grid/_modules_/grid/utils/getGridLocalization.ts
+++ b/packages/grid/_modules_/grid/utils/getGridLocalization.ts
@@ -1,5 +1,5 @@
 import { GridLocaleText } from '../models/api/gridLocaleTextApi';
-import { GridOptions } from '../models/gridOptions';
+import type { GridOptions } from '../models/gridOptions';
 import { getMuiVersion } from './utils';

 interface LocalizationV4 {
```

Otherwise, I would also be keen on dropping the custom bundling logic we use here and use the one of the main repository, it has superior features.

**Comment by fayez-nazzal** [comment]
any progress on this issue?

**Comment by flaviendelangle** [comment]
Yes, we are working on correctly separating the pro and free version to avoid bundling any of the pro feature in the free version.
This should also give us a cleaner view to perform other optimizations.

**Comment by masbaehr** [comment]
Hey am i doing something wrong? If i only need the free datagrid, did i import correctly? Right now the bundle grows about 300KB due to index-esm.js
```
 "@mui/x-data-grid": "^5.2.0",
```

```
import { DataGrid } from "@mui/x-data-grid";
```

![image](https://user-images.githubusercontent.com/38694044/145732168-a6179aa1-b368-4f20-a2a8-00ccf9140afa.png)

**Comment by ha-ku** [comment]
> Hey am i doing something wrong? If i only need the free datagrid, did i import correctly? Right now the bundle grows about 300KB due to index-esm.js
> 
> ```
>  "@mui/x-data-grid": "^5.2.0",
> ```
> 
> ```
> import { DataGrid } from "@mui/x-data-grid";
> ```
> 
> ![image](https://user-images.githubusercontent.com/38694044/145732168-a6179aa1-b368-4f20-a2a8-00ccf9140afa.png)

Any updates? I'm facing the same problem.

**Comment by flaviendelangle** [comment]
I intend to rework the bundling strategy to mimic the core
I did it on #3451 but for the DataGrid I need to do structural changes before which unfortunately takes time.
With that being said, the DataGrid is an heavy component with lots of code, I don't think the size will decrease dramatically.

**Comment by flaviendelangle** [comment]
For `debounce` we are now using `import { debounce } from '@mui/material/utils';`

I am updating the list

**Comment by oliviertassinari** [comment]
Most of the opportunities raised have been covered. I think that now our best next step to improve the bundle size is to invest into measurability: #5550

**Comment by akgupta0777** [comment]
Any progress on this one ? Data grid is still very heavy 333 KBs 🥲😯😯
![image](https://user-images.githubusercontent.com/51379307/200159988-e6935526-79ec-4bc2-ac85-b8177f64d1a8.png)

**Comment by andriijas** [comment]
@oliviertassinari  

In mui the recommended way to import to avoid exessive bundle size is:

```
import Alert from "@mui/material/Alert"
```
The equivalent in mui-x doesnt work:
```
import Datagrid  from "@mui/x-data-grid/DataGrid";
import GridColDef  from "@mui/x-data-grid/GridColDef";

```

Maybe this is something that can ease tree shaking in webpack?

**Comment by oliviertassinari** [comment]
> The equivalent in mui-x doesnt work:

@andriijas One level deep imports were created in Material UI for tree-shaking in **development mode** and only. With MUI X, components so far had a standalone npm package which brings most of the tree shaking in development mode.

A side note `GridColDef` is a type in your example, so not applicable.

**Comment by andriijas** [comment]
Ofc, was just writing up quick example to discuss. I bet all of you already knows best what’s possible and what not applicable. We will switch to mui table in our project bc we don’t actually have advanced table and no need for data grid and we will switch to dayjs. I think that’s the best for now. 

Happy new year!

**Comment by oliviertassinari** [comment]
> We will switch to mui table in our project bc we don’t actually have advanced table and no need for data grid

https://github.com/mui/mui-x/issues/7358 could maybe be a solution in the future.

**Comment by 00ricardo** [comment]
Follow up ⬆️

Is there any progress on this? This component is so amazing, its a shame that there is a lack of optimization in it.

What are your plans for this topic?

**Comment by oliviertassinari** [comment]
@00ricardo do you come with specific opportunities/problems or it's more of an overall request to focus on bundle size?

From https://bundlephobia.com/package/@mui/x-data-grid@7.12.0 it looks healthier many years later. Now, I haven't dove into the bundle tree map to see if there are important inefficiencies.
