### ISSUE TITLE
[NFR] Increase the awareness of the `DataGrid` in the community

### ISSUE THREAD

**Issue by DanailH** [mui/mui-x#2932]
### Summary 💡

The purpose of this issue is to track the effort required to achieve one of our OKRs for the quarter. As key results are private to the company they will not be shared here.

This is a wrapper issue. All the linked issues relevant to achieving this goal will be listed below:

- [x] https://github.com/mui-org/material-ui-x/issues/2933
- [x] https://github.com/mui-org/material-ui-x/issues/2934
- [x] https://github.com/mui-org/material-ui-x/issues/2398

**Comment by DanailH** [comment]
All of the linked issues have been completed.
