### ISSUE TITLE
[Umbrella] Row tree structure

### ISSUE THREAD

**Issue by flaviendelangle** [mui/mui-x#2994]
Issue to centralize all the topics related to the tree structure of the rows.
We try to keep as much as possible of the logic shared between the various features that need a tree structure.

Initial implementation: #2813

## Features relying on the tree structure

- #210 
- #212 
- #213 

## Improvements

- [ ] #3377 (see https://www.ag-grid.com/javascript-data-grid/server-side-model-grouping), 
- [ ] Do not re-apply the filtering on all the rows when toggling a row expansion
- [ ] #4248
- [x] #3428 
- [x] #4270 
- [ ] https://github.com/mui/mui-x/issues/4930

**Comment by flaviendelangle** [comment]
Closing this one, the new structure has been merged
