### ISSUE TITLE
[core] Make the premium plan available

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-x#3135]
We are close to being able to release the first iteration on the https://github.com/mui-org/material-ui-x/issues/212 feature. This should make us in a good position to make the Premium plan available in Q1 2022. This issue is meant to coordinate the work on the next steps. At a high level, I believe we have the following problems to resolve

Code **mui/mui-x**

- [x] 1. How do we ship the code on npm? Do we create a new npm package `@mui/x-data-grid-premium`? Do we expose a new component `DataGridPremium`? Or do we bundle everything? https://www.notion.so/mui-org/Shipping-the-high-tier-plan-782c6648a4ae4a0491a3d17d65087546
- [x] 2. #4090
- [x] 3. #3925
- [x] 4. #4507

Store **mui/mui-store**
- [x] 1. Our current pricing structure has several issues. Maybe it's time to revisit it https://www.notion.so/mui-org/Rework-pricing-structure-e780ad974ce64d99bc88a2a7b94a6c0a
- [x] 2. https://github.com/mui/mui-store/pull/162
- [x] 3. https://github.com/mui/mui-store/pull/155 
- [ ] 4. How will customers upgrade from Pro to Premium? https://www.notion.so/mui-org/Discounts-for-upgrades-to-Premium-5dd1867fba944c95856313de956a0e5a

Website **mui/material-ui**

- [x] 1. https://github.com/mui/material-ui/pull/32458

**Comment by flaviendelangle** [comment]
Did we defined how we were handling pro to premium upgrades ? This should be a classic use-case during the 1st months.
Some companies bought pro plan because the premium did not exist yet.

**Comment by oliviertassinari** [comment]
Adding item 8. for this, great point.

**Comment by flaviendelangle** [comment]
Moving to self service is important.
But I was more thinking financially. will we deduce the cost of their pro license purchase (proportionate to the remaining time) from their premium license cost ? If so, or if we do another type of discount for update, were would the information be written ?

**Comment by oliviertassinari** [comment]
I leave this to @mbrookes

**Comment by mbrookes** [comment]
> will we deduct the cost of their pro license purchase (proportionate to the remaining time) from their premium license cost ?

We lack the infrastructure to do that currently, except for purchases by PO, but even then, doing it manually would be a headache. I'd favor doing what we do now, and deduct the full cost of the pro license for customers who are in support. It's what we currently do for template upgrades.

**Comment by flaviendelangle** [comment]
@joserodolfofreitas we should probably adapt this section when premium is released to display one pro and one premium grid.

https://mui.com/components/data-grid/#commercial-version

**Comment by joserodolfofreitas** [comment]
Good point, @flaviendelangle. I added it to the todo list.

**Comment by oliviertassinari** [comment]
The new plan is live https://mui.com/pricing/.
