### ISSUE TITLE
[core] Release Premium plan

### ISSUE THREAD

**Issue by joserodolfofreitas** [mui/mui-x#4507]
# Motivation

As we approach the Premium plan's release. This issue coordinate the work required for the first step of https://www.notion.so/mui-org/MUI-X-Pricing-changes-2022-f17df701bf10406884a3204dcb8a3a3f

## Updates

- [x] Add a demo for Premium in contrast with the demos of Pro and MIT versions in [data grid's overview](https://mui.com/x/react-data-grid/).
- [x] Add plans Premium to the plans section https://mui.com/x/react-data-grid/getting-started/#plans
- [x] Update the support priority section in [X's overview](https://mui.com/x/advanced-components/)
- [x] Update the pricing page https://github.com/mui/material-ui/pull/32458

**Comment by joserodolfofreitas** [comment]
Closed with:
https://github.com/mui/material-ui/pull/32458
https://github.com/mui/mui-x/pull/4750
