### ISSUE TITLE
[pickers] Add codemods for breaking changes

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#6997]
The v6 for pickers is bringing quite a few breaking changes.
To ease users' migration we ought to try and cover as most changes with codemods as possible.

The codemod package can be [found here](https://github.com/mui/mui-x/tree/next/packages/x-codemod). It already contains all the core setup needed in order to add new codemods to it.

This is intended as an umbrella issue to group all the codemods needed for `v.6.x` migration.
Ideally as much migrations as possible should be provided with `preset-safe` codemod.

## The process of adding a new codemod
- One of the [existing codemods](https://github.com/mui/mui-x/tree/next/packages/x-codemod/src/v6.0.0) can be used as an example (i.e.: [localization-provider-rename-locale](https://github.com/mui/mui-x/tree/next/packages/x-codemod/src/v6.0.0/localization-provider-rename-locale))
- copy or create a new folder for your codemod
- all the relevant code that is eventually shipped to the user is in `index.ts`
- update/provide tests for your newly created codemod (test fixtures are authored as js files to allow as minimal syntax as you want—without triggering ts issues)
- if your codemod is safe to add to [`preset-safe`](https://github.com/mui/mui-x/tree/next/packages/x-codemod/src/v6.0.0/preset-safe)—update this codemod with your newly added codemod making sure the [codemods order is correct](https://github.com/mui/mui-x/blob/next/packages/x-codemod/src/v6.0.0/preset-safe/index.ts) if codemod is sensitive to that (i.e. separate props should firstly be migrated to `componentProps` and only later be passed through a codemod renaming `componentProps` to `slotProps` if we'd go with such approach)
- update [README](https://github.com/mui/mui-x/blob/next/packages/x-codemod/README.md) file with your newly added codemod
You can check [@mui/codemod](https://github.com/mui/material-ui/tree/master/packages/mui-codemod/src) for inspiration on more advanced migration cases.

## How to test your changes locally (on a different project)

P.S. `yarn link` does not create a `bin` command from a linked package
- run `build` with either `yarn workspace @mui/x-codemod build` or `yarn build` if you are in `src/packages/x-codemod`
- run `cd build && yarn pack`
- copy the built `7.tgz` file to the root of your project you want to run (test) the codemod in
- add `"@mui/x-codemod": "file:./<your_package_name>"` into your project dependencies
- run `yarn install`
- now you can run the codemod in the way you prefer (either through `npx @mui/x-codemod v6.0.0/preset-safe src` or by adding an `x-codemod` script in your project)
- caveat: testing iterative changes might result in a cached package version being used instead of your latest modification. You can  either use a unique package name (possibly quicker) each time or clean npm cache each time.

## Breaking changes requiring codemods
Breaking changes related to pickers [are documented here](https://next.mui.com/x/migration/migration-pickers-v5/) and relevant PRs are available [with applied filters](https://github.com/mui/mui-x/pulls?q=is%3Apr+label%3A%22component%3A+pickers%22+label%3A%22breaking+change%22+label%3Av6.x).

- [x] replace-left-arrow-button-slot [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-leftarrowbutton-slot) | [change PR](https://github.com/mui/mui-x/pull/5890)
- [x] replace-right-arrow-button-slot [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-rightarrowbutton-slot) | [change PR](https://github.com/mui/mui-x/pull/5890)
- [x] replace-dialog-prop [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-the-dialogprops-prop) | [change PR](https://github.com/mui/mui-x/pull/6381)
- [x] replace-paper-prop [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-the-paperprops-prop) | [change PR](https://github.com/mui/mui-x/pull/6381)
- [x] replace-popper-prop [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-the-popperprops-prop) | [change PR](https://github.com/mui/mui-x/pull/6381)
- [x] replace-transition-component-prop [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-the-transitioncomponent-prop) | [change PR](https://github.com/mui/mui-x/pull/6381)
- [x] replace-trap-focus-prop [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-the-trapfocusprops-prop) | [change PR](https://github.com/mui/mui-x/pull/6381)
- [ ] replace-render-day _(optional)_ [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-the-renderday-prop) | [change PR](https://github.com/mui/mui-x/pull/6293) — **possibly very hard or impossible to make a reliable codemod**
- [x] rename-localization-props [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-localization-props) | [change PR](https://github.com/mui/mui-x/pull/6233)
- [x] rename-locale-prop [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-localization-props) | [change PR](https://github.com/mui/mui-x/pull/6011)
- [x] rename-view-components [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-view-components) | [change PR](https://github.com/mui/mui-x/pull/6389) | [change PR](https://github.com/mui/mui-x/pull/6851)
- [x] rename-date-prop-on-view-components [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-view-components) | [change PR](https://github.com/mui/mui-x/pull/6128)
- [ ] rename-private-components _(optional)_ [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-view-components) | [change PR](https://github.com/mui/mui-x/pull/6550)
- [x] replace-toolbar-props-by-slot [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-toolbar-props-by-slot) | [change PR](https://github.com/mui/mui-x/pull/6445) | [change PR](https://github.com/mui/mui-x/pull/7498)
- [x] replace-tabs-props [doc](https://next.mui.com/x/migration/migration-pickers-v5/#replace-tabs-props) | [change PR](https://github.com/mui/mui-x/pull/6543) | [change PR](https://github.com/mui/mui-x/pull/7024)
- [x] replace-adapter-imports [doc](https://next.mui.com/x/migration/migration-pickers-v5/#extended-date-io-adapters) |  [relevant issue](https://github.com/mui/mui-x/issues/6470)
- [x] rename-should-disable-time [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-shoulddisabletime-prop) | [change PR](https://github.com/mui/mui-x/pull/7299)
- [ ] rename-next-components _(optional)_ [doc](https://next.mui.com/x/migration/migration-pickers-v5/#new-picker-components) | [change PR](https://github.com/mui/mui-x/pull/7345/files#diff-583d60010865b618442d1aad760dd6516a8d24d5d49fd3efa34cb5a90ff070fbR51)
- [x] rename-input-format-prop [doc](https://next.mui.com/x/migration/migration-pickers-v5/#rename-the-inputformat-prop) | [change PR](https://github.com/mui/mui-x/pull/6722)

**Comment by alexfauquette** [comment]
For the loacelText prop, I should import: https://github.com/mui/material-ui/pull/34430

**Comment by alexfauquette** [comment]
@LukasTy About `rename-should-disable-time` I don't know if we can do a codemod, or at least it should be not be in preset since there are two options to do the migration. 

By the way, there is a typo in the migration example: The argument name is `time`, but the method uses `value`. I don't know which one is the best

```diff
 <DateTimePicker
-  shouldDisableTime={(timeValue, view) => view === 'hours' && timeValue < 12}
+  shouldDisableTime={(time, view) => view === 'hours' && value.hour() < 12}
 />
```


About `rename-private-components` and `rename-next-components` it's feasible to have a codemod, but it will not be that much different from a search and replace.

**Comment by LukasTy** [comment]
> About `rename-should-disable-time` I don't know if we can do a codemod, or at least it should be not be in preset since there are two options to do the migration.

I do think that we should do the migration from `shouldDIsableTime` to `shouldDisableClock` as that is safe and shouldn't cause any issues.
But yes, the fact that the new `shouldDisableTime` is now more flexible should still be made clear 🙈 

> By the way, there is a typo in the migration example: The argument name is `time`, but the method uses `value`. I don't know which one is the best

🤦 I do think that `value` does sound a bit more correct, just because `time.hour()` seems a bit strange 🙈 

> About `rename-private-components` and `rename-next-components` it's feasible to have a codemod, but it will not be that much different from a search and replace.

Indeed, those are somewhat pointless as codemods and would probably cover a very small percentage of use-cases anyways. 👌 
I do agree that they can be omitted from the package. 👍

**Comment by alexfauquette** [comment]
OK, I will do the missing one + fix migration guide 👍

**Comment by LukasTy** [comment]
Closing this one as all the planned codemods for stable release have been added. 👍 
If we will need any further improvements or fixes, they can be tackled via separate issues.
