### ISSUE TITLE
[pickers] Remove `WrapperVariantContext` usage

### ISSUE THREAD

**Issue by LukasTy** [mui/mui-x#7372]
Created from https://github.com/mui/mui-x/pull/7105#discussion_r1048500282

`WrapperVariantContext` serves little purpose and in some cases causes issues (inconsistencies) if a component is used without this context.

Remove or replace by a prop from:
- [x] DateTimePickerTabs @LukasTy #7374
- [x] CalendarOrClockPicker `Will be removed with legacy pickers`
- [x] PickersMonth  @flaviendelangle #7382
- [x] Clock #8083
- [x] PickersYear @flaviendelangle #7382 
- [x] YearCalendar @flaviendelangle  #7382
- [x] DateRangeCalendar @flaviendelangle #7488
- [x] DateRangePickerView `Will be removed with legacy pickers`
- [ ] Remove `WrapperVariantContext` after legacy pickers are removed

**Comment by flaviendelangle** [comment]
I'm tagging my self on the one I'm working on :+1:
