### ISSUE TITLE
[DataGridPro] Filtering on the Header followup actions

### ISSUE THREAD

**Issue by MBilalShafi** [mui/mui-x#9034]
This one supersedes #7760 with the action items left over.

- [ ] #9243
- [x] 2. [Chrome only] Visual bug: scroll jump on keyboard navigation. 
  - Context https://github.com/mui/mui-x/pull/7760#discussion_r1188514018
  - Fix #9502
- [x] 3. A visual issue with compact density https://github.com/mui/mui-x/issues/13048 :
![image](https://github.com/mui/mui-x/assets/12609561/3423419c-0dc2-485f-8aa7-cc84dac08802)
- [x] 4. Adjust icons
  - Context #9049 
  - Fix https://github.com/mui/mui-x/pull/9181
- [x] 5. Improve floating label animation
  - Context https://github.com/mui/mui-x/pull/7760#discussion_r1199512574 
  - Fix https://github.com/mui/mui-x/pull/9181
- [x] 6. Restructure filtering docs for better discoverability
  - Fix #9074
- [x] 7. Bugs related to cell blur
  - Context https://github.com/mui/mui-x/issues/9034#issuecomment-1570343195
  - Fix https://github.com/mui/mui-x/pull/9181
- [x] 8. Dark mode border issue
  - Context https://github.com/mui/mui-x/issues/9034#issuecomment-1577956424
  - Fix https://github.com/mui/mui-x/pull/9181

**Comment by oliviertassinari** [comment]
Another one. This Pro feature is in the middle of the MIT page, and the page is quite big, I think that we could breakdown the page, move the Pro feature to its own page, not alienating the community.

**Comment by MBilalShafi** [comment]
> I think that we could break down the page into multiples

@oliviertassinari Yep that's a good idea, I've tried to do a similar thing in this PR: https://github.com/mui/mui-x/pull/9074

**Comment by oliviertassinari** [comment]
A bug related to the cell blur logic: The input label is still shrunk when the focus is out of the cell.

https://github.com/mui/mui-x/assets/3165635/811c7dc0-db52-4621-bb43-8636dcf2849c

https://mui.com/x/react-data-grid/filtering/#header-filters

**Comment by MBilalShafi** [comment]
> Enter blur the filter input. I think that we should test this with end-users. I got tricked by this again. I don't know if the filter is applied instantly, my instinct is to press Enter to run the filter but now, when I type again, nothing happens as the input is blurred.

This one is interesting, the behavior that filters are applied on debounce and not on enter is something that users already experienced with the regular filter panel, not sure about other users but for me, the loading icon that appears during typing is a nice visual feedback that depicts the filters are being applied in the background, but yes we can test this with users and see what most of the users think about it 👍 

If we change the behavior to apply the filter on <kbd>Enter</kbd> though, there's a nice way to stop differentiating between the cell and input field. When the user starts typing, the arrow keys are passed to the input, on pressing Enter, the filters are applied, and the focus is still on the input (cursor is blinking), but the arrow keys are now passed to the keyboard navigation (which again can pass to the input when user starts typing something). But I am not sure if this will look natural to the users 🤔 I'll try to do a demo to validate the idea.

**Comment by romgrk** [comment]
It feels a bit off to me that the separator between headers & header filters has more visual weight than the one between header filters & cells. I feel like if there is a bolder separator, it should be between the whole header section and the cells.

<img src="https://github.com/mui/mui-x/assets/1423607/7f282af5-269d-49b2-94a3-342c5931dca4" height="200" />

**Comment by MBilalShafi** [comment]
@romgrk Thank you for pointing it out, the border color was not properly adjusting with the dark mode, fixed it in this [commit](https://github.com/mui/mui-x/pull/9181/commits/b2e84c7a7356d13491fc7edb6c151a5c899e33e9).

**Comment by romgrk** [comment]
For the comment above, cc @gerdadesign I think?

**Comment by MBilalShafi** [comment]
> I wonder if we wouldn't be better off by placing the filters inside the column title cell. It would also save some vertical space if we can avoid having 2 separate rows for the headers & filters.

That's a nice idea, we discussed it multiple times previously and after discussing the pros and cons, we decided to go with the separate header row. For example: https://github.com/mui/mui-x/issues/4934#issuecomment-1251556983, https://github.com/mui/mui-x/issues/4934#issuecomment-1342749545

I agree, in the current implementation, the state with no filter value doesn't look ideal, as there's a white space on top and a white border near the bottom. Probably we can think about iterating the UI part a bit.

**Comment by MBilalShafi** [comment]
All the items have been covered except #9243 which has a separate issue to track, closing this umbrella issue.
