### ISSUE TITLE
[data grid] Recipes

### ISSUE THREAD

**Issue by cherniavskii** [mui/mui-x#9328]
This is an umbrella issue where we keep track of the recipes we want to add to our docs.

- [ ] https://github.com/mui/mui-x/issues/7596
- [ ] https://github.com/mui/mui-x/issues/7588
- [ ] https://github.com/mui/mui-x/issues/2429#issuecomment-1271495585
- [ ] https://github.com/mui/mui-x/issues/5976
- [ ] https://github.com/mui/mui-x/issues/7782
- [ ] https://github.com/mui/mui-x/issues/7860
- [ ] https://github.com/mui/mui-x/issues/7876
- [ ] https://github.com/mui/mui-x/issues/8860
- [ ] https://github.com/mui/mui-x/issues/2851
- [ ] https://github.com/mui/mui-x/issues/5506
- [ ] https://github.com/mui/mui-x/issues/4813
- [ ] https://github.com/mui/mui-x/issues/5381
- [ ] https://github.com/mui/mui-x/issues/4248
- [ ] https://github.com/mui/mui-x/issues/4127
